#include "compositors/display_backend.h"
#include "compositors/mango/mango_runtime.h"
#include "core/log.h"
#include "util/string_utils.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string>

namespace compositors::display {

  namespace {

    constexpr Logger kLog("mango_display");

    [[nodiscard]] std::filesystem::path outputsConfPath() {
      const char* xdg = std::getenv("XDG_CONFIG_HOME");
      std::filesystem::path base = xdg != nullptr && xdg[0] != '\0'
          ? std::filesystem::path(xdg)
          : std::filesystem::path(std::getenv("HOME")) / ".config";
      return base / "mango" / "noctalia" / "output.conf";
    }

    [[nodiscard]] std::string monitorRule(
        const std::string& name, int width, int height, int refreshHz, int x, int y, double scale, bool vrr, bool hdr
    ) {
      char buffer[512];
      std::snprintf(
          buffer, sizeof(buffer),
          "monitorrule=name:^%s$,width:%d,height:%d,refresh:%d,x:%d,y:%d,scale:%s,rr:0,vrr:%d,hdr:%d", name.c_str(),
          width, height, refreshHz, x, y, StringUtils::formatDotDecimal(scale).c_str(), vrr ? 1 : 0, hdr ? 1 : 0
      );
      return buffer;
    }

    bool parseRuleField(std::string_view rule, std::string_view field, std::string& out) {
      const auto start = rule.find(std::string(field) + ":");
      if (start == std::string_view::npos) {
        return false;
      }
      const auto valueStart = start + field.size() + 1;
      const auto end = rule.find(',', valueStart);
      out = std::string(
          rule.substr(valueStart, end == std::string_view::npos ? rule.size() - valueStart : end - valueStart)
      );
      return true;
    }

    bool parseRuleInt(std::string_view rule, std::string_view field, int& out) {
      std::string value;
      if (!parseRuleField(rule, field, value)) {
        return false;
      }
      try {
        out = std::stoi(value);
        return true;
      } catch (const std::exception&) {
        return false;
      }
    }

    bool parseRuleDouble(std::string_view rule, std::string_view field, double& out) {
      std::string value;
      if (!parseRuleField(rule, field, value)) {
        return false;
      }
      try {
        out = std::stod(value);
        return true;
      } catch (const std::exception&) {
        return false;
      }
    }

    // Enabled lines are active; `# `-prefixed lines are disabled outputs.
    [[nodiscard]] std::vector<OutputState> readRules(std::string& error) {
      std::vector<OutputState> outputs;
      std::ifstream file(outputsConfPath());
      if (!file.is_open()) {
        error = "noctalia output config not found";
        return outputs;
      }
      std::string line;
      while (std::getline(file, line)) {
        const auto trimmed = StringUtils::trim(line);
        bool enabled = true;
        if (trimmed.starts_with("#")) {
          enabled = false;
        }
        const auto pos = trimmed.find("monitorrule=");
        if (pos == std::string::npos) {
          continue;
        }
        const std::string rule = trimmed.substr(pos);
        std::string name;
        if (!parseRuleField(rule, "name", name) || name.size() < 2) {
          continue;
        }
        if (name.front() == '^') {
          name = name.substr(1);
        }
        if (name.back() == '$') {
          name.pop_back();
        }
        OutputState out;
        out.name = name;
        out.enabled = enabled;
        int width = 0;
        int height = 0;
        int refresh = 60;
        parseRuleInt(rule, "width", width);
        parseRuleInt(rule, "height", height);
        parseRuleInt(rule, "refresh", refresh);
        parseRuleInt(rule, "x", out.x);
        parseRuleInt(rule, "y", out.y);
        parseRuleDouble(rule, "scale", out.scale);
        int vrr = 0;
        int hdr = 0;
        parseRuleInt(rule, "vrr", vrr);
        parseRuleInt(rule, "hdr", hdr);
        out.vrr = vrr != 0;
        out.hdr = hdr != 0;
        if (out.scale <= 0.0) {
          out.scale = 1.0;
        }
        out.modes = {DisplayMode{width > 0 ? width : 1920, height > 0 ? height : 1080, refresh * 1000, false, true}};
        out.modeStr = std::to_string(out.modes[0].width)
            + "x"
            + std::to_string(out.modes[0].height)
            + "@"
            + formatRateHz(out.modes[0].refreshMhz);
        outputs.push_back(std::move(out));
      }
      return outputs;
    }

    [[nodiscard]] std::string writeRules(const std::map<std::string, OutputState>& target, std::string& error) {
      std::string content = "# Auto-generated by Noctalia - do not edit manually\n\n";
      for (const auto& [name, cfg] : target) {
        const auto current =
            static_cast<std::size_t>(std::clamp(cfg.currentModeIndex, 0, static_cast<int>(cfg.modes.size()) - 1));
        int width = 1920;
        int height = 1080;
        int refresh = 60;
        if (!cfg.modes.empty()) {
          width = cfg.modes[current].width;
          height = cfg.modes[current].height;
          refresh = static_cast<int>(std::lround(cfg.modes[current].refreshMhz / 1000.0));
        }
        const auto rule = monitorRule(name, width, height, refresh, cfg.x, cfg.y, cfg.scale, cfg.vrr, cfg.hdr);
        if (!cfg.enabled) {
          content += "# ";
        }
        content += rule;
        content.push_back('\n');
      }
      const auto path = outputsConfPath();
      std::error_code ec;
      std::filesystem::create_directories(path.parent_path(), ec);
      std::ofstream file(path, std::ios::trunc);
      if (!file.is_open()) {
        error = "failed to write noctalia output config";
        return {};
      }
      file << content;
      return path.string();
    }

  } // namespace

  DisplayBackendSpec mangoSpec(compositors::mango::MangoRuntime& runtime) {
    const auto reload = [&runtime]() { (void)runtime.dispatch("reload_config"); };
    return DisplayBackendSpec{
        .kind = "mango",
        .supportsHdr = true,
        .fetchArgs = []() { return std::vector<std::string>{}; },
        .parseFetch = [](std::string_view /*payload*/, std::string& error) { return readRules(error); },
        .composeAll = [reload](const std::map<std::string, OutputState>& target) -> std::vector<DisplayCommand> {
          std::string error;
          (void)writeRules(target, error);
          if (!error.empty()) {
            kLog.warn("{}", error);
          }
          return {DisplayCommand{{}, std::nullopt, reload}};
        },
        .composePositions = [reload](const std::map<std::string, OutputState>& target) -> std::vector<DisplayCommand> {
          std::string error;
          (void)writeRules(target, error);
          if (!error.empty()) {
            kLog.warn("{}", error);
          }
          return {DisplayCommand{{}, std::nullopt, reload}};
        },
    };
  }

} // namespace compositors::display
