#include "theme/builtin_schemes.h"

#include "render/core/color.h"

#include <array>

namespace noctalia::theme {

  namespace {

    constexpr std::array<BuiltinScheme, 10> kSchemes = {{
        {
            "Ayu",
            Palette{
                .primary = hex("#E6B450"),
                .onPrimary = hex("#0B0E14"),
                .secondary = hex("#AAD94C"),
                .onSecondary = hex("#0B0E14"),
                .tertiary = hex("#39BAE6"),
                .onTertiary = hex("#0B0E14"),
                .error = hex("#D95757"),
                .onError = hex("#0B0E14"),
                .surface = hex("#0B0E14"),
                .onSurface = hex("#D1D1C7"),
                .surfaceVariant = hex("#1e222a"),
                .onSurfaceVariant = hex("#8E959E"),
                .outline = hex("#565B66"),
                .shadow = hex("#000000"),
                .hover = hex("#39BAE6"),
                .onHover = hex("#0B0E14"),
            },
            Palette{
                .primary = hex("#FF8F40"),
                .onPrimary = hex("#F8F9FA"),
                .secondary = hex("#86B300"),
                .onSecondary = hex("#F8F9FA"),
                .tertiary = hex("#55B4D4"),
                .onTertiary = hex("#F8F9FA"),
                .error = hex("#E65050"),
                .onError = hex("#F8F9FA"),
                .surface = hex("#F8F9FA"),
                .onSurface = hex("#42474C"),
                .surfaceVariant = hex("#E4E6E9"),
                .onSurfaceVariant = hex("#6E757C"),
                .outline = hex("#8A9199"),
                .shadow = hex("#F8F9FA"),
                .hover = hex("#55B4D4"),
                .onHover = hex("#F8F9FA"),
            },
        },
        {
            "Catppuccin",
            Palette{
                .primary = hex("#cba6f7"),
                .onPrimary = hex("#11111b"),
                .secondary = hex("#fab387"),
                .onSecondary = hex("#11111b"),
                .tertiary = hex("#94e2d5"),
                .onTertiary = hex("#11111b"),
                .error = hex("#f38ba8"),
                .onError = hex("#11111b"),
                .surface = hex("#1e1e2e"),
                .onSurface = hex("#cdd6f4"),
                .surfaceVariant = hex("#313244"),
                .onSurfaceVariant = hex("#a3b4eb"),
                .outline = hex("#4c4f69"),
                .shadow = hex("#11111b"),
                .hover = hex("#94e2d5"),
                .onHover = hex("#11111b"),
            },
            Palette{
                .primary = hex("#8839ef"),
                .onPrimary = hex("#eff1f5"),
                .secondary = hex("#fe640b"),
                .onSecondary = hex("#eff1f5"),
                .tertiary = hex("#40a02b"),
                .onTertiary = hex("#eff1f5"),
                .error = hex("#d20f39"),
                .onError = hex("#dce0e8"),
                .surface = hex("#eff1f5"),
                .onSurface = hex("#4c4f69"),
                .surfaceVariant = hex("#ccd0da"),
                .onSurfaceVariant = hex("#6c6f85"),
                .outline = hex("#a5adcb"),
                .shadow = hex("#dce0e8"),
                .hover = hex("#40a02b"),
                .onHover = hex("#eff1f5"),
            },
        },
        {
            "Dracula",
            Palette{
                .primary = hex("#bd93f9"),
                .onPrimary = hex("#282A36"),
                .secondary = hex("#ff79c6"),
                .onSecondary = hex("#4e1d32"),
                .tertiary = hex("#8be9fd"),
                .onTertiary = hex("#003543"),
                .error = hex("#FF5555"),
                .onError = hex("#282A36"),
                .surface = hex("#282A36"),
                .onSurface = hex("#F8F8F2"),
                .surfaceVariant = hex("#44475A"),
                .onSurfaceVariant = hex("#d6d8e0"),
                .outline = hex("#5a5e77"),
                .shadow = hex("#282A36"),
                .hover = hex("#8be9fd"),
                .onHover = hex("#003543"),
            },
            Palette{
                .primary = hex("#8332f4"),
                .onPrimary = hex("#ffffff"),
                .secondary = hex("#ff1399"),
                .onSecondary = hex("#ffffff"),
                .tertiary = hex("#0398b9"),
                .onTertiary = hex("#ffffff"),
                .error = hex("#FF5555"),
                .onError = hex("#282A36"),
                .surface = hex("#f8f8f2"),
                .onSurface = hex("#282a36"),
                .surfaceVariant = hex("#e6e6ea"),
                .onSurfaceVariant = hex("#44475a"),
                .outline = hex("#cacad3"),
                .shadow = hex("#d6d8e0"),
                .hover = hex("#0398b9"),
                .onHover = hex("#ffffff"),
            },
        },
        {
            "Eldritch",
            Palette{
                .primary = hex("#37f499"),
                .onPrimary = hex("#171928"),
                .secondary = hex("#04d1f9"),
                .onSecondary = hex("#171928"),
                .tertiary = hex("#a48cf2"),
                .onTertiary = hex("#171928"),
                .error = hex("#f16c75"),
                .onError = hex("#171928"),
                .surface = hex("#212337"),
                .onSurface = hex("#ebfafa"),
                .surfaceVariant = hex("#292e42"),
                .onSurfaceVariant = hex("#ABB4DA"),
                .outline = hex("#3b4261"),
                .shadow = hex("#414868"),
                .hover = hex("#a48cf2"),
                .onHover = hex("#171928"),
            },
            Palette{
                .primary = hex("#37f499"),
                .onPrimary = hex("#171928"),
                .secondary = hex("#04d1f9"),
                .onSecondary = hex("#171928"),
                .tertiary = hex("#a48cf2"),
                .onTertiary = hex("#171928"),
                .error = hex("#f16c75"),
                .onError = hex("#171928"),
                .surface = hex("#ffffff"),
                .onSurface = hex("#171928"),
                .surfaceVariant = hex("#f2f4f8"),
                .onSurfaceVariant = hex("#3b4261"),
                .outline = hex("#b0b6c3"),
                .shadow = hex("#e0e3e8"),
                .hover = hex("#a48cf2"),
                .onHover = hex("#171928"),
            },
        },
        {
            "Gruvbox",
            Palette{
                .primary = hex("#b8bb26"),
                .onPrimary = hex("#282828"),
                .secondary = hex("#fabd2f"),
                .onSecondary = hex("#282828"),
                .tertiary = hex("#83a598"),
                .onTertiary = hex("#282828"),
                .error = hex("#fb4934"),
                .onError = hex("#282828"),
                .surface = hex("#282828"),
                .onSurface = hex("#fbf1c7"),
                .surfaceVariant = hex("#3c3836"),
                .onSurfaceVariant = hex("#ebdbb2"),
                .outline = hex("#57514e"),
                .shadow = hex("#282828"),
                .hover = hex("#83a598"),
                .onHover = hex("#282828"),
            },
            Palette{
                .primary = hex("#98971a"),
                .onPrimary = hex("#fbf1c7"),
                .secondary = hex("#d79921"),
                .onSecondary = hex("#fbf1c7"),
                .tertiary = hex("#458588"),
                .onTertiary = hex("#fbf1c7"),
                .error = hex("#cc241d"),
                .onError = hex("#fbf1c7"),
                .surface = hex("#fbf1c7"),
                .onSurface = hex("#3c3836"),
                .surfaceVariant = hex("#ebdbb2"),
                .onSurfaceVariant = hex("#7c6f64"),
                .outline = hex("#bdae93"),
                .shadow = hex("#d5c4a1"),
                .hover = hex("#458588"),
                .onHover = hex("#fbf1c7"),
            },
        },
        {
            "Kanagawa",
            Palette{
                .primary = hex("#76946a"),
                .onPrimary = hex("#1f1f28"),
                .secondary = hex("#c0a36e"),
                .onSecondary = hex("#1f1f28"),
                .tertiary = hex("#7e9cd8"),
                .onTertiary = hex("#1f1f28"),
                .error = hex("#c34043"),
                .onError = hex("#1f1f28"),
                .surface = hex("#1f1f28"),
                .onSurface = hex("#c8c093"),
                .surfaceVariant = hex("#2a2a37"),
                .onSurfaceVariant = hex("#717c7c"),
                .outline = hex("#363646"),
                .shadow = hex("#1f1f28"),
                .hover = hex("#7e9cd8"),
                .onHover = hex("#1f1f28"),
            },
            Palette{
                .primary = hex("#6f894e"),
                .onPrimary = hex("#f2ecbc"),
                .secondary = hex("#77713f"),
                .onSecondary = hex("#f2ecbc"),
                .tertiary = hex("#4d699b"),
                .onTertiary = hex("#f2ecbc"),
                .error = hex("#c84053"),
                .onError = hex("#f2ecbc"),
                .surface = hex("#f2ecbc"),
                .onSurface = hex("#545464"),
                .surfaceVariant = hex("#e5ddb0"),
                .onSurfaceVariant = hex("#8a8980"),
                .outline = hex("#cfc49c"),
                .shadow = hex("#f2ecbc"),
                .hover = hex("#4d699b"),
                .onHover = hex("#f2ecbc"),
            },
        },
        {
            "Noctalia",
            Palette{
                .primary = hex("#fff59b"),
                .onPrimary = hex("#0e0e43"),
                .secondary = hex("#a9aefe"),
                .onSecondary = hex("#0e0e43"),
                .tertiary = hex("#9BFECE"),
                .onTertiary = hex("#0e0e43"),
                .error = hex("#FD4663"),
                .onError = hex("#0e0e43"),
                .surface = hex("#070722"),
                .onSurface = hex("#f3edf7"),
                .surfaceVariant = hex("#11112d"),
                .onSurfaceVariant = hex("#7c80b4"),
                .outline = hex("#21215F"),
                .shadow = hex("#070722"),
                .hover = hex("#9BFECE"),
                .onHover = hex("#0e0e43"),
            },
            Palette{
                .primary = hex("#5d65f5"),
                .onPrimary = hex("#dadcff"),
                .secondary = hex("#8E93D8"),
                .onSecondary = hex("#dadcff"),
                .tertiary = hex("#0e0e43"),
                .onTertiary = hex("#fef29a"),
                .error = hex("#FD4663"),
                .onError = hex("#0e0e43"),
                .surface = hex("#e6e8fa"),
                .onSurface = hex("#0e0e43"),
                .surfaceVariant = hex("#eff0ff"),
                .onSurfaceVariant = hex("#4b55c8"),
                .outline = hex("#8288fc"),
                .shadow = hex("#f3edf7"),
                .hover = hex("#0e0e43"),
                .onHover = hex("#fef29a"),
            },
        },
        {
            "Nord",
            Palette{
                .primary = hex("#8fbcbb"),
                .onPrimary = hex("#2e3440"),
                .secondary = hex("#88c0d0"),
                .onSecondary = hex("#2e3440"),
                .tertiary = hex("#5e81ac"),
                .onTertiary = hex("#2e3440"),
                .error = hex("#bf616a"),
                .onError = hex("#2e3440"),
                .surface = hex("#2e3440"),
                .onSurface = hex("#eceff4"),
                .surfaceVariant = hex("#3b4252"),
                .onSurfaceVariant = hex("#d8dee9"),
                .outline = hex("#505a70"),
                .shadow = hex("#2e3440"),
                .hover = hex("#5e81ac"),
                .onHover = hex("#2e3440"),
            },
            Palette{
                .primary = hex("#5e81ac"),
                .onPrimary = hex("#eceff4"),
                .secondary = hex("#64adc2"),
                .onSecondary = hex("#eceff4"),
                .tertiary = hex("#6fa9a8"),
                .onTertiary = hex("#eceff4"),
                .error = hex("#bf616a"),
                .onError = hex("#eceff4"),
                .surface = hex("#eceff4"),
                .onSurface = hex("#2e3440"),
                .surfaceVariant = hex("#e5e9f0"),
                .onSurfaceVariant = hex("#4c566a"),
                .outline = hex("#c5cedd"),
                .shadow = hex("#d8dee9"),
                .hover = hex("#6fa9a8"),
                .onHover = hex("#eceff4"),
            },
        },
        {
            "Rosé Pine",
            Palette{
                .primary = hex("#ebbcba"),
                .onPrimary = hex("#191724"),
                .secondary = hex("#9ccfd8"),
                .onSecondary = hex("#191724"),
                .tertiary = hex("#31748f"),
                .onTertiary = hex("#e0def4"),
                .error = hex("#eb6f92"),
                .onError = hex("#191724"),
                .surface = hex("#191724"),
                .onSurface = hex("#e0def4"),
                .surfaceVariant = hex("#26233a"),
                .onSurfaceVariant = hex("#908caa"),
                .outline = hex("#403d52"),
                .shadow = hex("#191724"),
                .hover = hex("#524f67"),
                .onHover = hex("#e0def4"),
            },
            Palette{
                .primary = hex("#d7827e"),
                .onPrimary = hex("#faf4ed"),
                .secondary = hex("#56949f"),
                .onSecondary = hex("#faf4ed"),
                .tertiary = hex("#286983"),
                .onTertiary = hex("#faf4ed"),
                .error = hex("#b4637a"),
                .onError = hex("#faf4ed"),
                .surface = hex("#fffaf3"),
                .onSurface = hex("#575279"),
                .surfaceVariant = hex("#f2e9e1"),
                .onSurfaceVariant = hex("#797593"),
                .outline = hex("#dfdad9"),
                .shadow = hex("#faf4ed"),
                .hover = hex("#cecacd"),
                .onHover = hex("#575279"),
            },
        },
        {
            "Tokyo-Night",
            Palette{
                .primary = hex("#7aa2f7"),
                .onPrimary = hex("#16161e"),
                .secondary = hex("#bb9af7"),
                .onSecondary = hex("#16161e"),
                .tertiary = hex("#9ece6a"),
                .onTertiary = hex("#16161e"),
                .error = hex("#f7768e"),
                .onError = hex("#16161e"),
                .surface = hex("#1a1b26"),
                .onSurface = hex("#c0caf5"),
                .surfaceVariant = hex("#24283b"),
                .onSurfaceVariant = hex("#9aa5ce"),
                .outline = hex("#353D57"),
                .shadow = hex("#15161e"),
                .hover = hex("#9ece6a"),
                .onHover = hex("#16161e"),
            },
            Palette{
                .primary = hex("#2e7de9"),
                .onPrimary = hex("#e1e2e7"),
                .secondary = hex("#9854f1"),
                .onSecondary = hex("#e1e2e7"),
                .tertiary = hex("#587539"),
                .onTertiary = hex("#e1e2e7"),
                .error = hex("#f52a65"),
                .onError = hex("#e1e2e7"),
                .surface = hex("#e1e2e7"),
                .onSurface = hex("#3760bf"),
                .surfaceVariant = hex("#d0d5e3"),
                .onSurfaceVariant = hex("#6172b0"),
                .outline = hex("#b4b5b9"),
                .shadow = hex("#a8aecb"),
                .hover = hex("#587539"),
                .onHover = hex("#e1e2e7"),
            },
        },
    }};

  } // namespace

  std::span<const BuiltinScheme> builtinSchemes() { return kSchemes; }

  const BuiltinScheme* findBuiltinScheme(std::string_view name) {
    for (const auto& scheme : kSchemes) {
      if (scheme.name == name) {
        return &scheme;
      }
    }
    return nullptr;
  }

} // namespace noctalia::theme
