[colors]
ansi = [
    "{{ colors.surface.default.hex }}",
    "{{ colors.error.default.hex }}",
    "{{ colors.primary.default.hex }}",
    "{{ colors.tertiary.default.hex }}",
    "{{ colors.on_primary_container.default.hex }}",
    "{{ colors.on_secondary_container.default.hex }}",
    "{{ colors.secondary.default.hex }}",
    "{{ colors.on_surface.default.hex }}",
]
background = "{{ colors.background.default.hex }}"
brights = [
    "{{ colors.surface_bright.default.hex }}",
    "{{ colors.error.default.hex }}",
    "{{ colors.primary.default.hex }}",
    "{{ colors.tertiary.default.hex }}",
    "{{ colors.on_primary_container.default.hex }}",
    "{{ colors.on_secondary_container.default.hex }}",
    "{{ colors.secondary.default.hex }}",
    "{{ colors.on_surface.default.hex }}",
]
compose_cursor = "{{ colors.on_surface.default.hex }}"
cursor_bg = "{{ colors.on_surface.default.hex }}"
cursor_border = "{{ colors.on_surface.default.hex }}"
cursor_fg = "{{ colors.surface_variant.default.hex }}"
foreground = "{{ colors.on_surface.default.hex }}"
scrollbar_thumb = "{{ colors.on_surface.default.hex }}"
selection_bg = "{{ colors.on_primary.default.hex }}"
selection_fg = "{{ colors.primary.default.hex }}"
split = "{{ colors.on_surface.default.hex }}"
visual_bell = "{{ colors.surface_variant.default.hex }}"

[colors.indexed]
16 = "{{ colors.secondary.default.hex }}"
17 = "{{ colors.on_surface.default.hex }}"

[colors.tab_bar]
background = "{{ colors.surface_variant.default.hex }}"
inactive_tab_edge = "{{ colors.outline.default.hex }}"

[colors.tab_bar.active_tab]
bg_color = "{{ colors.primary.default.hex }}"
fg_color = "{{ colors.on_primary.default.hex }}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "{{ colors.surface.default.hex }}"
fg_color = "{{ colors.on_surface.default.hex }}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "{{ colors.surface_variant.default.hex }}"
fg_color = "{{ colors.on_surface_variant.default.hex }}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "{{ colors.surface.default.hex }}"
fg_color = "{{ colors.on_surface.default.hex }}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "{{ colors.secondary.default.hex }}"
fg_color = "{{ colors.on_secondary.default.hex }}"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
aliases = ["Noctalia"]
name = "Noctalia"
wezterm_version = "Always"
