[theme]
background = "{{colors.surface.default.hex}}"
primary = "{{colors.primary.default.hex}}"
secondary = "{{colors.secondary.default.hex}}"
title = "{{colors.tertiary.default.hex}}"
playing = "{{colors.secondary_fixed_dim.default.hex}}"
playing_bg = "{{colors.surface.default.hex}}"
highlight = "{{colors.primary.default.hex}}"
highlight_bg = "{{colors.primary_container.default.hex}}"
playing_selected = "{{colors.secondary_fixed_dim.default.hex}}"
error = "{{colors.surface.default.hex}}"
error_bg = "{{colors.error.default.hex}}"
statusbar = "{{colors.tertiary.default.hex}}"
statusbar_bg = "{{colors.surface.default.hex}}"
statusbar_progress = "{{colors.tertiary.default.hex}}"
cmdline = "{{colors.tertiary.default.hex}}"
cmdline_bg = "{{colors.surface.default.hex}}"
