[Colors]
accent={{colors.on_surface_variant.default.hex}}
background={{colors.surface.default.hex}}
background_fullscreen={{colors.surface.default.hex}}
folderview={{colors.surface.default.hex}}
folderview_topbar={{colors.surface_variant.default.hex}}
icons={{colors.primary_container.default.hex | auto_lightness 15}}
overlay={{colors.surface_variant.default.hex}}
overlay_text={{colors.on_surface.default.hex}}
scrollbar={{colors.surface_bright.default.hex}}
text={{colors.on_surface.default.hex}}
tid=3
widget={{colors.surface_variant.default.hex}}
widget_border={{colors.primary.default.hex}}
